name: Ruby

on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.0.2"
          bundler-cache: true
      - name: Run the default task
        env:
        PARKING_TICKET_PASSWORD: ${{ secrets.PARKING_TICKET_PASSWORD }}
        PARKING_TICKET_USERNAME: ${{ secrets.PARKING_TICKET_USERNAME }}
        PARKING_TICKET_LICENSEPLATE: ${{ secrets.PARKING_TICKET_LICENSEPLATE }}
        PARKING_TICKET_ZIPCODE: ${{ secrets.PARKING_TICKET_ZIPCODE }}
        PARKING_TICKET_CARDNUMBER: ${{ secrets.PARKING_TICKET_CARDNUMBER }}

        run: bundle exec rake
